version: '3.8'

services:
  app:
    image: ${DOCKER_REGISTRY-}demodesignparternweb
    container_name: demodesignpartern.web
    build:
      context: .
      dockerfile: DemoDesignPartern.Web/Dockerfile
    ports:
      - "5023:5023"
      - "7090:7090"
  # db:
  #   image: mcr.microsoft.com/mssql/server:latest
  #   environment:
  #     - SA_PASSWORD=Your_password123
  #     - ACCEPT_EULA=Y
  #   ports:
  #     - "1433:1433"
  #   volumes:
  #     - sqlserverdata:/var/opt/mssql

volumes:
  sqlserverdata:
