FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER app
WORKDIR /app
EXPOSE 5023
EXPOSE 7090

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["DemoDesignPartern.Web/DemoDesignPartern.Web.csproj", "DemoDesignPartern.Web/"]
RUN dotnet restore "./DemoDesignPartern.Web/./DemoDesignPartern.Web.csproj"
COPY . .
WORKDIR "/src/DemoDesignPartern.Web"
RUN dotnet build "./DemoDesignPartern.Web.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./DemoDesignPartern.Web.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "DemoDesignPartern.Web.dll"]